# Generated by Django 3.1.2 on 2020-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date',
        ),
        migrations.AddField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
