# Generated by Django 3.1.3 on 2021-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201206_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='products_recommend',
            field=models.IntegerField(default='0'),
        ),
    ]
