# Generated by Django 3.1.3 on 2021-01-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_products_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='products_recommend',
            field=models.TextField(max_length=255),
        ),
    ]
