# Generated by Django 3.1.2 on 2021-01-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_orderitem_customerinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customerInfo',
        ),
    ]
