# Generated by Django 3.1.3 on 2021-01-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rateproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateProduct',
        ),
    ]
