# Generated by Django 3.1.3 on 2021-01-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_delete_rateproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_recommendations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
