# Generated by Django 3.1.3 on 2021-01-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210127_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_recommendations',
            field=models.TextField(),
        ),
    ]
