# Generated by Django 3.1.3 on 2021-01-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210127_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_recommendations',
            field=models.IntegerField(default='0'),
        ),
    ]
