# Generated by Django 3.1.3 on 2021-01-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210127_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
